---
name: 'Quality Checks'

on: [pull_request]

permissions:
  contents: read

jobs:
  quality-checks:
    name: 'Linters'
    # yamllint disable-line rule:line-length
    uses: garretpatten/quality-checks/.github/workflows/quality-checks.yaml@72ec29587c0f3cc59d9d3a35acbe04215e46abe5 # master
    with:
      eslint_run: true
      hadolint_run: true
      jq_run: true
      markdownlint_run: true
      prettier_run: true
      ruff_run: true
      shellcheck_run: true
      taplo_run: true
      yamllint_run: true
    secrets: inherit
