name: 'Security Guardrails'

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  scans:
    name: 'Scans'
    # yamllint disable-line rule:line-length
    uses: garretpatten/security-guardrails/.github/workflows/security-guardrails.yaml@651edab515f4b6a180940ba128e4d7e25dcbf815 # master
    with:
      opengrep_run: true
      supply_chain_run: true
      trufflehog_run: true
    secrets: inherit
